version: '3'
services:
  server:
    image: 'interest-api-server'
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8080:8080'
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5431:5432' # map port 5432 from container to 5431 to our localhost
